set -e

sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

flatpak install flathub com.spotify.Client -y
flatpak install flathub net.cozic.joplin_desktop -y
flatpak install flathub com.github.mdh34.quickdocs -y
flatpak install flathub com.getpostman.Postman -y
flatpak install flathub com.obsproject.Studio -y
flatpak install flathub io.github.shiftey.Desktop -y
flatpak install flathub io.typora.Typora -y
flatpak install flathub com.discordapp.Discord -y
flatpak install flathub org.telegram.desktop -y
flatpak install flathub org.videolan.VLC -y
flatpak install flathub io.mpv.Mpv -y
flatpak install flathub info.smplayer.SMPlayer -y
flatpak install flathub org.kde.kdenlive -y
flatpak install flathub com.belmoussaoui.Decoder -y
flatpak install flathub com.diy_fever.DIYLayoutCreator -y
flatpak install flathub com.github.junrrein.PDFSlicer -y
flatpak install flathub net.codeindustry.MasterPDFEditor -y
flatpak install flathub com.github.alecaddd.sequeler -y
flatpak install flathub io.dbeaver.DBeaverCommunity -y
flatpak install flathub com.github.gi_lom.dialect -y
flatpak install flathub com.github.johnfactotum.Foliate -y
flatpak install flathub com.github.robertsanseries.ciano -y
flatpak install flathub com.leinardi.gst -y
flatpak install flathub io.gitlab.librewolf-community -y
flatpak install flathub net.meijn.onvifviewer -y
flatpak install flathub de.haeckerfelix.Shortwave -y
flatpak install flathub ch.openboard.OpenBoard -y
flatpak install flathub io.github.hakuneko.HakuNeko -y
flatpak install flathub org.shotcut.Shotcut -y
flatpak install flathub com.google.AndroidStudio -y
flatpak install flathub org.remmina.Remmina -y
flatpak install flathub org.kde.okular -y
flatpak install flathub org.kde.krita -y
flatpak install flathub org.gimp.GIMP -y
flatpak install flathub org.blender.Blender -y
flatpak install flathub org.flameshot.Flameshot -y
flatpak install flathub org.libreoffice.LibreOffice -y
flatpak install flathub org.onlyoffice.desktopeditors -y
flatpak install flathub org.qbittorrent.qBittorrent -y
flatpak install flathub com.calibre_ebook.calibre -y
flatpak install flathub de.haeckerfelix.AudioSharing -y
flatpak install flathub org.gnome.gitlab.somas.Apostrophe -y
flatpak install flathub org.fedoraproject.MediaWriter -y
flatpak install flathub com.rafaelmardojai.Blanket -y
flatpak install flathub com.github.geigi.cozy -y
flatpak install flathub dev.geopjr.Collision -y
flatpak install flathub com.github.maoschanz.drawing -y
flatpak install flathub de.haeckerfelix.Fragments -y
flatpak install flathub org.gustavoperedo.FontDownloader -y
flatpak install flathub com.github.hugolabe.Wike -y
flatpak install flathub re.sonny.Tangram -y
flatpak install flathub org.gnome.gitlab.YaLTeR.VideoTrimmer -y
flatpak install flathub com.rafaelmardojai.WebfontKitGenerator -y
flatpak install flathub com.github.liferooter.textpieces -y
flatpak install flathub org.gnome.Solanum -y
flatpak install flathub de.haeckerfelix.Shortwave -y
flatpak install flathub com.rafaelmardojai.SharePreview -y
flatpak install flathub com.github.alexhuntley.Plots -y
flatpak install flathub com.belmoussaoui.Obfuscate -y
flatpak install flathub com.gitlab.newsflash -y
flatpak install flathub io.github.seadve.Mousai -y
flatpak install flathub com.adrienplazas.Metronome -y
flatpak install flathub fr.romainvigier.MetadataCleaner -y
flatpak install flathub io.github.lainsce.Khronos -y
flatpak install flathub io.github.seadve.Kooha -y
flatpak install flathub org.gnome.Connections -y
flatpak install flathub org.gnome.Boxes -y
flatpak install flathub org.gnome.SoundRecorder -y
flatpak install flathub org.gnome.GHex -y
